### ISSUE TITLE
I can't open the website. And can you share your data with me?

### ISSUE THREAD

**Issue by sherpahu** [pyaf/load_forecasting#26]
The web site "http://forecast.energyandsystems.com" could not be loaded.  
Besides, I don't know how to get the data from "http://www.delhisldc.org". Could you please share it with if it's ok for you.  
Thanks in advance!

**Comment by pyaf** [comment]
Hey @sherpahu http://forecast.energyandsystems.com is down due to some reasons. 
You can use `load_scrap` to download the data from delhisldc website

**Comment by sherpahu** [comment]
Thanks a lot for your kindness!  
However, the weather scraper doesn't work.  
It is a pity that Wunderground doesn't provide free scraping api anymore. Perhaps, that's the reason that your web is down.  
Did you try any other weather scrapers?
